/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GameWeb3 } from "./GameWeb3";
export * as factories from "./factories";
export { GameWeb3__factory } from "./factories/GameWeb3__factory";
